/**
 * O que importa saber do jungler deles na seleção: quando ele ganka forte
 * e o que fazer contra. Só campeões que vivem na jungle; se o time deles
 * travou um destes, é quase certo que é o jungler.
 */
export const JUNGLERS = {
  'Lee Sin': 'gank forte nível 3, ward aos 2:45',
  'Elise': 'gank forte nível 3, dive cedo',
  'Xin Zhao': 'gank forte nível 3',
  'Jarvan IV': 'gank forte nível 3, flash pra escapar da ult',
  'Nunu & Willump': 'gank nível 2 e rouba camp, joga perto da torre',
  'Warwick': 'gank nível 2 se você estiver com pouca vida',
  'Shaco': 'invade e ganka nível 2, ward no arbusto da lane',
  'Briar': 'gank forte nível 3, foge das ganks dela sem flash',
  "Kha'Zix": 'forte nível 3 em quem está sozinho',
  'Rengar': 'gank pelo arbusto, ward no arbusto da lane',
  'Nidalee': 'invade e ganka cedo, joga recuado',
  'Viego': 'gank nível 3, fica forte com kill',
  'Graves': 'farma cedo, ganka com nível 4',
  'Kindred': 'farma e invade cedo',
  'Kayn': 'fraco cedo, forte depois da forma',
  'Master Yi': 'farma até nível 6, depois entra',
  'Karthus': 'farma, ult global depois do 6',
  'Amumu': 'gank nível 6, respeita a ult',
  'Fiddlesticks': 'gank nível 6 pelo arbusto, ward nos arbustos',
  'Lillia': 'farma cedo, forte depois do 6',
  'Hecarim': 'gank forte com velocidade, joga recuado',
  'Vi': 'gank forte nível 6, ult te trava',
  'Evelynn': 'invisível depois do 6, ward não vê ela',
  'Zac': 'gank de longe pelo pulo, joga longe de parede',
  'Sejuani': 'gank forte com CC, espera o jungler seu',
  'Diana': 'forte nível 6, entra em cima do time',
  'Ekko': 'gank nível 3, forte com o segundo item',
  'Jax': 'forte cedo no 1x1',
  'Volibear': 'gank nível 3 com stun, dive cedo',
  'Skarner': 'gank forte com a ult, joga longe da parede',
  'Udyr': 'gank cedo com stun, joga recuado',
  'Wukong': 'gank nível 3 pelo arbusto',
  'Rek\'Sai': 'gank rápido pelos túneis',
  'Ivern': 'gank com arbusto, ward nos arbustos',
  'Taliyah': 'gank forte com o muro, joga longe de parede',
  'Poppy': 'gank forte perto de parede',
  'Naafiri': 'gank forte nível 3 em quem está sozinho',
  'Gwen': 'farma cedo, forte depois',
  'Trundle': 'gank cedo com pilar, joga recuado',
  'Nocturne': 'forte depois do 6, ult global',
  'Rammus': 'gank rápido, tank',
  'Maokai': 'gank nível 3 com CC',
  'Talon': 'gank pelos muros, aparece de repente',
  'Zed': 'gank forte nível 3',
  'Bel\'Veth': 'farma cedo, forte depois',
  'Shyvana': 'farma, forte depois do 6',
  'Olaf': 'gank forte cedo, sem CC nele',
  'Pantheon': 'gank forte nível 3, ult global',
  'Vex': 'gank com dash deles',
  'Morgana': 'farma, CC forte',
  'Kled': 'gank forte com a ult',
  'Yorick': 'farma, empurra sozinho',
  'Sylas': 'gank nível 3, rouba ult',
  'Ambessa': 'gank forte nível 3',
  'Qiyana': 'gank forte pelo arbusto',
  'Dr. Mundo': 'farma, tank',
  'Zyra': 'gank com CC',
  'Brand': 'gank com CC',
  'Teemo': 'ward nos arbustos: cogumelo',
  'Gragas': 'gank nível 3 com CC, joga longe de parede',
  'Nautilus': 'gank com CC, ward cedo',
  'Rumble': 'gank com ult por trás da wave, não fica na lane',
  'Twitch': 'gank invisível: ward no arbusto de lane, não avança sem visão',
  'Sett': 'gank com o E puxando: não fica perto da parede',
  'Darius': 'gank lento, mas dive forte: recua com metade da vida',
  'Aatrox': 'gank com Q por cima de parede: não fica encostado nela',
};
